# Generated by Django 3.2 on 2026-04-26 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id_predio', models.AutoField(db_column='id_predio', primary_key=True, serialize=False)),
                ('nombre_predio', models.CharField(max_length=150)),
                ('municipio', models.CharField(max_length=100)),
                ('parroquia', models.CharField(blank=True, max_length=100, null=True)),
                ('comunidad', models.CharField(blank=True, max_length=150, null=True)),
                ('superficie', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('este', models.CharField(blank=True, max_length=50, null=True)),
                ('norte', models.CharField(blank=True, max_length=50, null=True)),
                ('tenencia', models.CharField(max_length=50)),
                ('vialidad', models.CharField(max_length=50)),
                ('corrales', models.IntegerField(default=0)),
                ('vaqueras', models.IntegerField(default=0)),
                ('silos', models.IntegerField(default=0)),
                ('lagunas', models.IntegerField(default=0)),
                ('casas', models.IntegerField(default=0)),
                ('salas_ordeno', models.IntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'predios',
            },
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_rif', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'productores',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_explotacion', models.CharField(max_length=50)),
                ('registro_sanitario', models.BooleanField(default=False)),
                ('registro_productivo', models.BooleanField(default=False)),
                ('registro_reproductivo', models.BooleanField(default=False)),
                ('registro_financiero', models.BooleanField(default=False)),
                ('predio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.predio')),
            ],
            options={
                'db_table': 'produccion',
            },
        ),
        migrations.CreateModel(
            name='Infraestructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrales', models.IntegerField(default=0)),
                ('galpones', models.IntegerField(default=0)),
                ('vaqueras', models.IntegerField(default=0)),
                ('cochineras', models.IntegerField(default=0)),
                ('silos', models.IntegerField(default=0)),
                ('caballerizas', models.IntegerField(default=0)),
                ('feedlot', models.IntegerField(default=0)),
                ('lagunas', models.IntegerField(default=0)),
                ('salas_ordeno', models.IntegerField(default=0)),
                ('queseras', models.IntegerField(default=0)),
                ('casas', models.IntegerField(default=0)),
                ('trapiches', models.IntegerField(default=0)),
                ('establos', models.IntegerField(default=0)),
                ('predio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.predio')),
            ],
            options={
                'db_table': 'infraestructura',
            },
        ),
        migrations.CreateModel(
            name='PredioServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.predio')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicio')),
            ],
            options={
                'db_table': 'predio_servicio',
                'unique_together': {('predio', 'servicio')},
            },
        ),
    ]
