# Generated by Django 3.2 on 2026-04-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_predio', models.CharField(max_length=255)),
                ('codigo_catastral', models.CharField(max_length=100, unique=True)),
                ('actividad', models.CharField(max_length=20)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_suelo', models.CharField(max_length=50)),
                ('clima', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=100)),
                ('parroquia', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=255)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('productor_nombre', models.CharField(max_length=255)),
                ('productor_telefono', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('punto_referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('productor_cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('cedula_imagen', models.FileField(blank=True, null=True, upload_to='cedulas/')),
            ],
            options={
                'db_table': 'predios',
            },
        ),
    ]
