# Generated by Django 6.0.1 on 2026-06-08 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id_predio', models.AutoField(db_column='id_predio', primary_key=True, serialize=False)),
                ('nombre_predio', models.CharField(max_length=150)),
                ('municipio', models.CharField(max_length=100)),
                ('parroquia', models.CharField(blank=True, max_length=100, null=True)),
                ('comunidad', models.CharField(blank=True, max_length=150, null=True)),
                ('centro_poblado', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('superficie', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coordenadas', models.CharField(blank=True, help_text='Latitud, Longitud', max_length=100, null=True)),
                ('tipo_propiedad', models.CharField(blank=True, max_length=50, null=True)),
                ('tenencia', models.CharField(max_length=100)),
                ('vialidad', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('caracterizacion_completada', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'predios',
            },
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_rif', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'productores',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquinariaSeleccionada', models.JSONField(default=list)),
                ('maquinaria_ruedas', models.JSONField(default=dict)),
                ('implementos', models.JSONField(default=dict)),
                ('riego', models.JSONField(default=dict)),
                ('otros_equipos', models.JSONField(default=dict)),
                ('predio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maquinaria', to='core.predio')),
            ],
            options={
                'db_table': 'maquinarias',
            },
        ),
        migrations.CreateModel(
            name='LicenciaHierro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_hierro', models.CharField(max_length=100)),
                ('numero_licencia', models.CharField(max_length=100)),
                ('organismo_emisor', models.CharField(max_length=100)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('certificado_pdf', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.predio')),
            ],
            options={
                'db_table': 'licencias_hierro',
            },
        ),
        migrations.CreateModel(
            name='Infraestructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrales', models.IntegerField(default=0)),
                ('galpones', models.IntegerField(default=0)),
                ('vaqueras', models.IntegerField(default=0)),
                ('cochineras', models.IntegerField(default=0)),
                ('silos', models.IntegerField(default=0)),
                ('caballerizas', models.IntegerField(default=0)),
                ('feedlot', models.IntegerField(default=0)),
                ('lagunas', models.IntegerField(default=0)),
                ('salas_ordeno', models.IntegerField(default=0)),
                ('queseras', models.IntegerField(default=0)),
                ('casas', models.IntegerField(default=0)),
                ('trapiches', models.IntegerField(default=0)),
                ('establos', models.IntegerField(default=0)),
                ('predio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infraestructura', to='core.predio')),
            ],
            options={
                'db_table': 'infraestructura',
            },
        ),
        migrations.CreateModel(
            name='ExistenciaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especiesSeleccionadas', models.JSONField(default=list)),
                ('vacunos', models.JSONField(default=dict)),
                ('capacidadVacuna', models.JSONField(default=dict)),
                ('bufalinos', models.JSONField(default=dict)),
                ('capacidadBufalina', models.JSONField(default=dict)),
                ('equinos', models.JSONField(default=dict)),
                ('capacidadEquina', models.JSONField(default=dict)),
                ('ovinos', models.JSONField(default=dict)),
                ('capacidadOvina', models.JSONField(default=dict)),
                ('porcinos', models.JSONField(default=dict)),
                ('capacidadPorcina', models.JSONField(default=dict)),
                ('caprinos', models.JSONField(default=dict)),
                ('capacidadCaprino', models.JSONField(default=dict)),
                ('conejos', models.JSONField(default=dict)),
                ('capacidadCunicola', models.JSONField(default=dict)),
                ('aves', models.JSONField(default=dict)),
                ('capacidadAvesCorral', models.JSONField(default=dict)),
                ('apicultura', models.JSONField(default=dict)),
                ('capacidadApicultura', models.JSONField(default=dict)),
                ('predio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='existencia_animal', to='core.predio')),
            ],
            options={
                'db_table': 'existencia_animal',
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_explotacion', models.CharField(max_length=50)),
                ('registro_sanitario', models.BooleanField(default=False)),
                ('registro_productivo', models.BooleanField(default=False)),
                ('registro_reproductivo', models.BooleanField(default=False)),
                ('registro_financiero', models.BooleanField(default=False)),
                ('predio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='produccion', to='core.predio')),
            ],
            options={
                'db_table': 'produccion',
            },
        ),
        migrations.AddField(
            model_name='predio',
            name='productor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predios', to='core.productor'),
        ),
        migrations.CreateModel(
            name='RubroVegetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubro', models.CharField(max_length=150)),
                ('hectareas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('riego', models.CharField(blank=True, max_length=100, null=True)),
                ('ciclo_productivo', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_produccion', models.CharField(blank=True, max_length=100, null=True)),
                ('produccion_estimada', models.CharField(blank=True, max_length=100, null=True)),
                ('destino', models.CharField(blank=True, max_length=100, null=True)),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubros_vegetales', to='core.predio')),
            ],
            options={
                'db_table': 'rubros_vegetales',
            },
        ),
        migrations.CreateModel(
            name='PredioServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.predio')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicio')),
            ],
            options={
                'db_table': 'predio_servicio',
                'unique_together': {('predio', 'servicio')},
            },
        ),
    ]
