# Generated by Django 6.0.1 on 2026-06-14 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='existenciaanimal',
            old_name='apicultura',
            new_name='apicola',
        ),
        migrations.RenameField(
            model_name='existenciaanimal',
            old_name='aves',
            new_name='avicola',
        ),
        migrations.RenameField(
            model_name='existenciaanimal',
            old_name='bufalinos',
            new_name='bovinos',
        ),
        migrations.RenameField(
            model_name='existenciaanimal',
            old_name='capacidadApicultura',
            new_name='bubalinos',
        ),
        migrations.RenameField(
            model_name='existenciaanimal',
            old_name='capacidadAvesCorral',
            new_name='capacidadApicola',
        ),
        migrations.RenameField(
            model_name='existenciaanimal',
            old_name='capacidadBufalina',
            new_name='capacidadAvicola',
        ),
        migrations.RenameField(
            model_name='existenciaanimal',
            old_name='capacidadVacuna',
            new_name='capacidadBovina',
        ),
        migrations.RenameField(
            model_name='existenciaanimal',
            old_name='conejos',
            new_name='capacidadBubalina',
        ),
        migrations.RenameField(
            model_name='existenciaanimal',
            old_name='vacunos',
            new_name='cunicola',
        ),
    ]
