# Generated by Django 3.2 on 2026-05-28 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_actualizacion_predio'),
    ]

    operations = [
       # migrations.RenameField(
        #    model_name='predio',
       #     old_name='este',
       #     new_name='tipo_propiedad',
       # ),
       
        migrations.RemoveField(
            model_name='predio',
            name='casas',
        ),
        migrations.RemoveField(
            model_name='predio',
            name='corrales',
        ),
        migrations.RemoveField(
            model_name='predio',
            name='lagunas',
        ),
        migrations.RemoveField(
            model_name='predio',
            name='norte',
        ),
        migrations.RemoveField(
            model_name='predio',
            name='salas_ordeno',
        ),
        migrations.RemoveField(
            model_name='predio',
            name='silos',
        ),
        migrations.RemoveField(
            model_name='predio',
            name='vaqueras',
        ),
        migrations.AddField(
            model_name='predio',
            name='centro_poblado',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='coordenadas',
            field=models.CharField(blank=True, help_text='Latitud, Longitud', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='productor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predios', to='core.productor'),
        ),
        migrations.AlterField(
            model_name='infraestructura',
            name='predio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infraestructura', to='core.predio'),
        ),
        migrations.AlterField(
            model_name='predio',
            name='tenencia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='predio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='produccion', to='core.predio'),
        ),
        migrations.CreateModel(
            name='RubroVegetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubro', models.CharField(max_length=150)),
                ('hectareas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('riego', models.CharField(blank=True, max_length=100, null=True)),
                ('ciclo_productivo', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_produccion', models.CharField(blank=True, max_length=100, null=True)),
                ('produccion_estimada', models.CharField(blank=True, max_length=100, null=True)),
                ('destino', models.CharField(blank=True, max_length=100, null=True)),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubros_vegetales', to='core.predio')),
            ],
            options={
                'db_table': 'rubros_vegetales',
            },
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquinariaSeleccionada', models.JSONField(default=list)),
                ('maquinaria_ruedas', models.JSONField(default=dict)),
                ('implementos', models.JSONField(default=dict)),
                ('riego', models.JSONField(default=dict)),
                ('otros_equipos', models.JSONField(default=dict)),
                ('predio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maquinaria', to='core.predio')),
            ],
            options={
                'db_table': 'maquinarias',
            },
        ),
        migrations.CreateModel(
            name='ExistenciaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especiesSeleccionadas', models.JSONField(default=list)),
                ('vacunos', models.JSONField(default=dict)),
                ('capacidadVacuna', models.JSONField(default=dict)),
                ('bufalinos', models.JSONField(default=dict)),
                ('capacidadBufalina', models.JSONField(default=dict)),
                ('equinos', models.JSONField(default=dict)),
                ('capacidadEquina', models.JSONField(default=dict)),
                ('ovinos', models.JSONField(default=dict)),
                ('capacidadOvina', models.JSONField(default=dict)),
                ('porcinos', models.JSONField(default=dict)),
                ('capacidadPorcina', models.JSONField(default=dict)),
                ('caprinos', models.JSONField(default=dict)),
                ('capacidadCaprino', models.JSONField(default=dict)),
                ('conejos', models.JSONField(default=dict)),
                ('capacidadCunicola', models.JSONField(default=dict)),
                ('aves', models.JSONField(default=dict)),
                ('capacidadAvesCorral', models.JSONField(default=dict)),
                ('apicultura', models.JSONField(default=dict)),
                ('capacidadApicultura', models.JSONField(default=dict)),
                ('predio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='existencia_animal', to='core.predio')),
            ],
            options={
                'db_table': 'existencia_animal',
            },
        ),
    ]
