# Generated by Django 3.2 on 2026-04-26 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_predio_productor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predio',
            name='casas',
        ),
        migrations.RemoveField(
            model_name='predio',
            name='corrales',
        ),
        migrations.RemoveField(
            model_name='predio',
            name='lagunas',
        ),
        migrations.RemoveField(
            model_name='predio',
            name='salas_ordeno',
        ),
        migrations.RemoveField(
            model_name='predio',
            name='silos',
        ),
        migrations.RemoveField(
            model_name='predio',
            name='vaqueras',
        ),
        migrations.AlterField(
            model_name='infraestructura',
            name='predio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infraestructura', to='core.predio'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='predio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='produccion', to='core.predio'),
        ),
    ]
