# Generated by Django 6.0.1 on 2026-07-12 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_apicultura_existenciaanimal_apicola_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenciahierro',
            name='organismo_emisor',
        ),
    ]
