# Generated by Django 3.2 on 2026-04-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20260426_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='predio',
            name='centro_poblado',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='tipo_propiedad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='predio',
            name='tenencia',
            field=models.CharField(max_length=100),
        ),
    ]
