# Generated by Django 6.0.1 on 2026-07-12 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_licenciahierro_organismo_emisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenciahierro',
            name='codigo_hierro',
        ),
        migrations.RemoveField(
            model_name='licenciahierro',
            name='numero_licencia',
        ),
    ]
