# Generated by Django 6.0.1 on 2026-07-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_licenciahierro_codigo_hierro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenciahierro',
            name='activa',
            field=models.BooleanField(default=True, help_text='Indica si la licencia está vigente y aprobada'),
        ),
    ]
