# Generated by Django 3.2 on 2026-05-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20260426_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predio',
            name='este',
        ),
        migrations.RemoveField(
            model_name='predio',
            name='norte',
        ),
        migrations.AddField(
            model_name='predio',
            name='coordenadas',
            field=models.CharField(blank=True, help_text='Latitud, Longitud', max_length=100, null=True),
        ),
    ]
