# Generated by Django 6.0.1 on 2026-05-18 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20260512_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistenciaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especiesSeleccionadas', models.JSONField(default=list)),
                ('vacunos', models.JSONField(default=dict)),
                ('capacidadVacuna', models.JSONField(default=dict)),
                ('bufalinos', models.JSONField(default=dict)),
                ('capacidadBufalina', models.JSONField(default=dict)),
                ('equinos', models.JSONField(default=dict)),
                ('capacidadEquina', models.JSONField(default=dict)),
                ('ovinos', models.JSONField(default=dict)),
                ('capacidadOvina', models.JSONField(default=dict)),
                ('porcinos', models.JSONField(default=dict)),
                ('capacidadPorcina', models.JSONField(default=dict)),
                ('caprinos', models.JSONField(default=dict)),
                ('capacidadCaprino', models.JSONField(default=dict)),
                ('conejos', models.JSONField(default=dict)),
                ('capacidadCunicola', models.JSONField(default=dict)),
                ('aves', models.JSONField(default=dict)),
                ('capacidadAvesCorral', models.JSONField(default=dict)),
                ('apicultura', models.JSONField(default=dict)),
                ('capacidadApicultura', models.JSONField(default=dict)),
                ('predio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='existencia_animal', to='core.predio')),
            ],
            options={
                'db_table': 'existencia_animal',
            },
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquinariaSeleccionada', models.JSONField(default=list)),
                ('maquinaria_ruedas', models.JSONField(default=dict)),
                ('implementos', models.JSONField(default=dict)),
                ('riego', models.JSONField(default=dict)),
                ('otros_equipos', models.JSONField(default=dict)),
                ('predio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maquinarias', to='core.predio')),
            ],
            options={
                'db_table': 'maquinarias',
            },
        ),
        migrations.CreateModel(
            name='RubroVegetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubro', models.CharField(max_length=150)),
                ('hectareas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('riego', models.CharField(blank=True, max_length=100, null=True)),
                ('ciclo_productivo', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_produccion', models.CharField(blank=True, max_length=100, null=True)),
                ('produccion_estimada', models.CharField(blank=True, max_length=100, null=True)),
                ('destino', models.CharField(blank=True, max_length=100, null=True)),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubros_vegetales', to='core.predio')),
            ],
            options={
                'db_table': 'rubros_vegetales',
            },
        ),
    ]
