# Generated by Django 3.2 on 2026-08-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_licenciahierro_activa'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministradorSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('usuario', models.CharField(max_length=100, unique=True)),
                ('clave', models.CharField(max_length=255)),
                ('rol', models.CharField(default='Administrador Maestro', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'administradores_sistema',
            },
        ),
    ]
