# Generated by Django 6.0.1 on 2026-05-24 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_existenciaanimal_maquinaria_rubrovegetal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaria',
            name='predio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maquinaria', to='core.predio'),
        ),
    ]
