# Generated by Django 3.2 on 2026-08-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_administradorsistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradorsistema',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='administradorsistema',
            name='rol',
            field=models.CharField(default='Administrador Municipal', max_length=100),
        ),
    ]
