# Generated by Django 6.0.1 on 2026-09-27 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_noticia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenciahierro',
            name='fecha_vencimiento',
        ),
    ]
