# Generated by Django 3.2 on 2026-10-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_licenciahierro_fecha_vencimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150)),
                ('accion', models.CharField(max_length=50)),
                ('modulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bitacora_auditoria',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
