# Generated by Django 3.2 on 2026-10-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_bitacoraauditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiaPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias_pendientes/')),
                ('empleado', models.CharField(default='Empleado', max_length=150)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
