# Generated by Django 3.2 on 2026-10-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_noticiapendiente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(default='agrosistema@barinas.gob.ve', max_length=254)),
                ('telefono', models.CharField(default='(0273) 300-0000', max_length=50)),
            ],
            options={
                'db_table': 'configuracion_contacto',
            },
        ),
    ]
