# Generated by Django 3.2 on 2026-10-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_configuracioncontacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='predio',
            name='estado',
            field=models.CharField(default='activo', max_length=50),
        ),
        migrations.AddField(
            model_name='predio',
            name='inhabilitado',
            field=models.BooleanField(default=False),
        ),
    ]
